name: Bug report
description: Something not working as expected? 🐞
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Ensure that the bug is not not fixed in recent releases. 
        Ensure that you will not create a duplicate: Use the GitHub issue search.
        For community help, please use discussions.

  - type: textarea
    id: stacktrace
    attributes:
      label: Error stacktrace (if any)
      description: Error stacktrace
    validations:
      required: false
